In [1]:
import pandas as pd
import datetime

## Read Data

In [2]:
all_data = pd.read_csv("train.csv")

In [3]:
# summarize the shape of the dataset
all_data.shape

(387229, 136)

Split the DATE coulmn to 3 seperated columns named month, year and weekday

In [114]:
# from datetime import date
# import datetime

# df['Day'] = df['DATE'].apply(lambda x: 
#                       (date(datetime.datetime.strptime(x,"%Y-%m-%d").year,datetime.datetime.strptime(x,"%Y-%m-%d").month,
#                       datetime.datetime.strptime(x,"%Y-%m-%d").day)-date(2019,4,10)).days)
# df.drop(['DATE'],axis=1,inplace=True)

In [4]:
all_data['month'] = all_data['DATE'].apply(lambda x: datetime.datetime.strptime(x,"%Y-%m-%d").month)  
all_data['year'] = all_data['DATE'].apply(lambda x: datetime.datetime.strptime(x,"%Y-%m-%d").year)                                                                         
all_data['weekday'] = all_data['DATE'].apply(lambda x: datetime.datetime.strptime(x,"%Y-%m-%d").weekday())

In [17]:
#Remove date column
all_data = all_data.drop(columns='DATE')

KeyError: ignored

In [6]:
# summarize the shape of the dataset
all_data.shape

(387229, 138)

In [119]:
# summarize each variable
print(all_data.describe())

             SITE_ID  CELL_TYPE_Macro  ...           year        weekday
count  621300.000000    621300.000000  ...  621300.000000  621300.000000
mean     1315.745534         0.921777  ...    2019.113333       3.006667
std       751.146117         0.268523  ...       0.317000       1.999990
min         0.000000         0.000000  ...    2019.000000       0.000000
25%       663.000000         1.000000  ...    2019.000000       1.000000
50%      1328.000000         1.000000  ...    2019.000000       3.000000
75%      1965.000000         1.000000  ...    2019.000000       5.000000
max      2604.000000         1.000000  ...    2020.000000       6.000000

[8 rows x 138 columns]

In [42]:
df = pd.DataFrame(all_data)

In [43]:
df.head()

   SITE_ID  CELL_TYPE_Macro  CELL_TYPE_Mobil  ...  month  year  weekday
0      146                1                0  ...      4  2019        2
1      146                1                0  ...      4  2019        3
2      146                1                0  ...      4  2019        4
3      146                1                0  ...      4  2019        5
4      146                1                0  ...      4  2019        6

[5 rows x 138 columns]

Split the origin DataFrame to subdataframes and sort them according to the duration days (3,7,14)

In [50]:
categorical_df = df.loc[: ,'CELL_TYPE_Macro':'CELL_TYPE_micro'] + df.loc[: ,'GEOGRAPHIC_CLUSTER_K_0':'GEOGRAPHIC_CLUSTER_K_9']
aircon_sum_wo_df = df.loc[:, 'aircon_sum_wo_prev7d' : 'aircon_sum_target_next14d']
N_TRANSPORTED_SITES_df = df.loc[:,'N_TRANSPORTED_SITES']
Numerical_df = df.loc[: , 'mean_temperature_prev7d':'min_pressure_f_next7d']
Numerical_df = Numerical_df.reindex(sorted(Numerical_df.columns, reverse=True), axis=1)
alarm_df = df.loc[: , 'equipment_sum_alarms_prev14d':'temperature_sum_alarms_prev3d']
persistance_df = (df.loc[:, 'equipment_max_persistance_prev7d': 'temperature_min_persistance_prev3d'])
persistance_df = persistance_df.reindex(sorted(persistance_df.columns, reverse=True), axis=1)
skewKurt_df = df.loc[:,'skew_equipment_alarms_prev14d': 'kurt_temperature_alarms_prev14d']
Date_df = df.loc[:,'month':'weekday']

In [51]:
Numerical_df.head()

   min_wind_speed_prev7d  ...  max_humidity_f_next14d
0                    5.0  ...                    89.0
1                    5.0  ...                    89.0
2                    5.0  ...                    89.0
3                    5.0  ...                    89.0
4                    5.0  ...                    89.0

[5 rows x 60 columns]

In [ ]:
persistance_df.head()

In [149]:
numerical_dic = {'aircon_sum_wo_prev':0, 'temperature_prev7d':3,'temperature_prev3d':6, 'rain_mm_prev7d': 9, 'rain_mm_prev3d': 12, 'humidity_prev7d' : 15,'humidity_prev3d':18, 'wind_speed_prev7d':21 , 'wind_speed_prev3d':24, 'wind_speed_prev7d' : 27, 'wind_speed_prev3d': 30, 'pressure_prev7d':33, 'pressure_prev3d': 36, 'temperature_f_next14d': 39, 'temperature_f_next7d': 42, 'rain_mm_f_next14d':45, 'rain_mm_f_next7d':48, 'humidity_f_next14d':51, 'humidity_f_next7d' : 54, 'speed_f_next14d':57, 'speed_f_next7d':60, 'pressure_f_next14d':63, 'pressure_f_next7d':66,       }

In [150]:
def new_numerical_df(numerical_dic, Numerical_df):
  i = 0
  while(i<len(numerical_dic)):
    if list(numerical_dic.keys())[i] == 'aircon_sum_wo_prev':
      index=2
    else:
      index = 3
    
    df_new = Numerical_df[Numerical_df.columns[(list(numerical_dic.values())[i]):(list(numerical_dic.values())[i]+index)]]
    Numerical_df[list(numerical_dic.keys())[i]] = df_new.mean(axis=1)

    i= i+1


  Numerical_df = Numerical_df.drop(columns = ['aircon_sum_wo_prev7d','aircon_sum_wo_prev14d'])
  Numerical_df=Numerical_df.drop(Numerical_df.columns.to_series()['mean_temperature_prev7d':'min_pressure_f_next7d'], axis=1)
  return Numerical_df

In [151]:
New_Numerical = new_numerical_df(numerical_dic, Numerical_df)

In [152]:
New_Numerical.head()

   aircon_sum_target_next14d  ...  pressure_f_next7d
0                          0  ...                0.0
1                          0  ...                0.0
2                          0  ...                0.0
3                          0  ...                0.0
4                          0  ...                0.0

[5 rows x 77 columns]

In [154]:
New_Numerical.describe()

       aircon_sum_target_next14d  ...  pressure_f_next7d
count              621300.000000  ...      621300.000000
mean                    0.005767  ...           1.832162
std                     0.075721  ...          14.305171
min                     0.000000  ...           0.000000
25%                     0.000000  ...           0.000000
50%                     0.000000  ...           0.000000
75%                     0.000000  ...           0.333333
max                     1.000000  ...         748.000000

[8 rows x 77 columns]

In [ ]:
# aircon_sum_wo_prev = Numerical_df.loc[: , "aircon_sum_wo_prev7d":"aircon_sum_wo_prev14d"]
# Numerical_df['ind_aircon_sum_wo_prev'] = aircon_sum_wo_prev.mean(axis=1)
# Numerical_df = Numerical_df.drop(columns=['aircon_sum_wo_prev7d','aircon_sum_wo_prev14d'] , axis = 1)

# temperature_prev7d = Numerical_df.loc[: , "mean_temperature_prev7d":"min_temperature_prev7d"]
# Numerical_df['ind_temperature_prev7d'] = temperature_prev7d.mean(axis=1)
# Numerical_df = Numerical_df.drop(columns=['mean_temperature_prev7d', 'max_temperature_prev7d', 'min_temperature_prev7d'] , axis = 1)

# temperature_prev3d = Numerical_df.loc[: , "mean_temperature_prev3d":"min_temperature_prev3d"]
# Numerical_df['ind_temperature_prev3d'] = temperature_prev3d.mean(axis=1)
# Numerical_df = Numerical_df.drop(columns=['mean_temperature_prev3d', 'max_temperature_prev3d', 'min_temperature_prev3d'] , axis = 1)

# rain_mm__prev7d = Numerical_df.loc[: , "mean_rain_mm_prev7d":"min_rain_mm_prev7d"]
# Numerical_df['ind_temperature_prev7d'] = temperature_prev7d.mean(axis=1)
# Numerical_df = Numerical_df.drop(columns=['mean_temperature_prev7d', 'max_temperature_prev7d', 'min_temperature_prev7d'] , axis = 1)



# Numerical_df['ind_temperature_prev'] = df.loc[: , "aircon_sum_wo_prev7d":"aircon_sum_wo_prev14d"].mean(axis=1)
# df = df.drop(columns=['aircon_sum_wo_prev7d','aircon_sum_wo_prev14d'] , axis = 1)

In [ ]:
# numerical_dic = {'aircon_sum_wo_prev':0}
# def new_numerical_df(indicator, Numerical_df):
#   numerical_dic = {'aircon_sum_wo_prev':0}

#   if indicator = 'aircon_sum_wo_prev':
#     i=2
#   else:
#     i = 3

#   df_new = Numerical_df[Numerical_df.columns[numerical_dic[indicator]:numerical_dic[indicator]+i]]
#   Numerical_df[indicator] = df_new.mean(axis=1)

#   New_Numerical_df=Numerical_df.drop(Numerical_df.columns.to_series()['aircon_sum_wo_prev7d':'aircon_sum_wo_prev14d'], axis=1)
#   return New_Numerical_df

In [ ]:
# def Merge_Min_Max_Mean(df):
#   categorical_df = df.loc[: , 'SITE_ID':'GEOGRAPHIC_CLUSTER_K_9']
#   Numerical_df = df.loc[: , 'aircon_sum_wo_prev7d':'kurt_temperature_alarms_prev14d']
#   column_index = 0
#   # i=3
#   # Numerical_df['ind_temperature_prev7d'] = Numerical_df.loc[:,i:i+3].mean(axis=1)
#   df['ind_aircon_sum_wo_prev'] = df.loc[: , "aircon_sum_wo_prev7d":"aircon_sum_wo_prev14d"].mean(axis=1)